apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-petclinic
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic
spec:
  selector:
    app: spring-petclinic
  ports:
  - port: 9010
    targetPort: 9010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-petclinic
  name: spring-petclinic
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
      labels:
        app: spring-petclinic
    spec:
      containers:
      # modify the following line with your Docker Hub account name
      - image: index.docker.io/anthonyvetter/spring-petclinic:latest
        name: spring-petclinic
        ports:
        - containerPort: 9010
